# SHRUTI  MISHRA

# TASK-1 Email spam detection model 


## Simplbyte


In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [18]:
spam_df=pd.read_csv("spam_ham_dataset.csv")


In [19]:
spam_df


Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3           4685  spam  Subject: photoshop , windows , office . cheap ...   
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...   
...          ...   ...                                                ...   
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...   
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...   
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...   
5169        1409   ham  Subject: industrial worksheets for august 2000...   
5170        4807  spam  Subject: important online banking alert\r\ndea...   

      label_num  
0             0  
1             0  
2             0  
3             1  
4             0  
...         ...  
5166          0  
5167          0  
5168          0  
5169          0  
5170          1  

[5171 rows x 4 columns]

In [20]:
df.shape

(5171, 4)

In [21]:
spam_df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [22]:
spam_df.isna()


Unnamed: 0  label   text  label_num
0          False  False  False      False
1          False  False  False      False
2          False  False  False      False
3          False  False  False      False
4          False  False  False      False
...          ...    ...    ...        ...
5166       False  False  False      False
5167       False  False  False      False
5168       False  False  False      False
5169       False  False  False      False
5170       False  False  False      False

[5171 rows x 4 columns]

In [23]:
spam_df.describe()

Unnamed: 0    label_num
count  5171.000000  5171.000000
mean   2585.000000     0.289886
std    1492.883452     0.453753
min       0.000000     0.000000
25%    1292.500000     0.000000
50%    2585.000000     0.000000
75%    3877.500000     1.000000
max    5170.000000     1.000000

In [24]:
spam_df.isna().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [25]:
spam_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  5171 non-null   int64 
 1   label       5171 non-null   object
 2   text        5171 non-null   object
 3   label_num   5171 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 161.7+ KB


In [26]:
spam_df.describe()

Unnamed: 0    label_num
count  5171.000000  5171.000000
mean   2585.000000     0.289886
std    1492.883452     0.453753
min       0.000000     0.000000
25%    1292.500000     0.000000
50%    2585.000000     0.000000
75%    3877.500000     1.000000
max    5170.000000     1.000000

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [28]:
spam_df.groupby('label').describe()

Unnamed: 0                                                         \
           count    mean          std     min      25%     50%      75%   
label                                                                     
ham       3672.0  1835.5  1060.159422     0.0   917.75  1835.5  2753.25   
spam      1499.0  4421.0   432.868340  3672.0  4046.50  4421.0  4795.50   

              label_num                                     
          max     count mean  std  min  25%  50%  75%  max  
label                                                       
ham    3671.0    3672.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
spam   5170.0    1499.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

In [29]:
spam_df['spam'] = spam_df['label_num']

In [30]:
spam_df

Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3           4685  spam  Subject: photoshop , windows , office . cheap ...   
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...   
...          ...   ...                                                ...   
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...   
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...   
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...   
5169        1409   ham  Subject: industrial worksheets for august 2000...   
5170        4807  spam  Subject: important online banking alert\r\ndea...   

      label_num  spam  
0             0     0  
1             0     0  
2             0     0  
3             1     1  
4             0     0  
...         ...   ...  
5166          0     0  
5167          0     0  
5168          0     0  
5169          0     0  
5170          1     1  

[5171 rows x 5 columns]

In [31]:
x_train, x_test, y_train, y_test = train_test_split(spam_df.text,spam_df.spam, test_size = 0.25)

In [32]:
x_train

4088    Subject: guaranteed satisfaction ! great price...
2139    Subject: archived great shots of california li...
4902    Subject: deal 107937 for 1 / 2000\r\ndaren ,\r...
3063    Subject: calpine daily gas nomination\r\n>\r\n...
770     Subject: hpl nom for may 10 , 2001\r\n( see at...
                              ...                        
5020    Subject: enron / hpl actuals for september 26 ...
1283    Subject: meter # 0989814 - gmt , inc . - 1 / 0...
2612    Subject: re : shut - in of meter 989842\r\ni n...
557     Subject: re : inquiry ?\r\nbecky ,\r\ncan we g...
3176    Subject: hpl nom for march 22 , 2001\r\n( see ...
Name: text, Length: 3878, dtype: object

In [33]:
x_train.describe()

count                                                  3878
unique                                                 3762
top       Subject: calpine daily gas nomination\r\n>\r\n...
freq                                                     14
Name: text, dtype: object

In [34]:
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [35]:
x_train_count

<3878x44019 sparse matrix of type '<class 'numpy.int64'>'
	with 341899 stored elements in Compressed Sparse Row format>

In [36]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 5, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [38]:
email_ham = ["hey wanna meet up today?"]
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([1], dtype=int64)

In [39]:
email_spam = ["reward money click!"]
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1], dtype=int64)

In [40]:
x_test_count = cv.transform(x_test)
model.score(x_test_count, y_test)

0.9721577726218097

### accuracy = 97%